// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Resume.Data.Context;
using System;

namespace Resume.Data.Migrations
{
    [DbContext(typeof(ResumeContext))]
    partial class ResumeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("resume_api.Model.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Curriculum");
                });

            modelBuilder.Entity("resume_api.Model.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurriculumId");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("resume_api.Model.Educacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurriculumId");

                    b.Property<string>("Establecimiento");

                    b.Property<string>("Nivel")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Educacion");
                });

            modelBuilder.Entity("resume_api.Model.Experiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo");

                    b.Property<int>("CurriculumId");

                    b.Property<string>("DescripcionTareas");

                    b.Property<string>("Empresa");

                    b.Property<DateTime?>("FechaFin");

                    b.Property<DateTime?>("FechaInicio");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("resume_api.Model.Curso", b =>
                {
                    b.HasOne("resume_api.Model.Curriculum")
                        .WithMany("Cursos")
                        .HasForeignKey("CurriculumId");
                });

            modelBuilder.Entity("resume_api.Model.Educacion", b =>
                {
                    b.HasOne("resume_api.Model.Curriculum")
                        .WithMany("Educacion")
                        .HasForeignKey("CurriculumId");
                });

            modelBuilder.Entity("resume_api.Model.Experiencia", b =>
                {
                    b.HasOne("resume_api.Model.Curriculum")
                        .WithMany("Experiencias")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
